#!/bin/bash

if [ "$#" -ne 2 ]; then
    echo "Illegal number of parameters"
    echo "please follow pattern ./<scriptPath> <region> <table_name>"
    exit 1
fi

table_name="gateway.stg.device_infos"
device_id="084de6e4-22a8-4cd9-9ca8-2f999bc9a141"
key="'{
	    \"device_id\": {
	    	\"S\": \"$device_id\"
	    }
	  }'"


region="$1"
table="$2"


command="aws dynamodb get-item --region $region --table-name $table --key $key"
echo $command

# -z string: True if the string is null (an empty string)
result="$(eval $command)"
echo "$result"		
