#!/bin/bash
#region="kafka1.oemv2.us-west-2.wtpgs.net:2181"	
#topic="stg.mcs-events.raw"
#By-default offset is "Latest"

if [ "$#" -ne 4 ]; then
    echo "Illegal number of parameters"
    echo "please follow pattern ./<scriptPath> <account> <region> <topic> <patternToSearch>"
    exit 1
fi

scriptPath="../kafka_2.11-0.10.1.1/bin/kafka-console-consumer.sh"
account="$1"
region="$2"
topic="$3"  
patternToSearch="$4"

zookeeper="kafka1.$account.$region.wtpgs.net:2181"

command="./$scriptPath --zookeeper $zookeeper --topic $topic"
echo $command

#   grep -q:
#	    do not write anything to standard output.   Exit  immedi-
#       ately  with  zero status if any match is found, even if an error
#       was detected. 

eval $command 2>&1 | grep "$patternToSearch"
